<wsdl:definitions name="git_soa_project_pocess" targetNamespace="http://xmlns.oracle.com/GIT_SOA_APPLICATION/git_soa_project/git_soa_project_pocess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/GIT_SOA_APPLICATION/git_soa_project/git_soa_project_pocess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://IBASE139.ibaseit.com:12101/soa-infra/services/default/git_soa_project!1.0/WSDLs/git_soa_project_pocess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="git_soa_project_pocess">
        <plnk:role name="git_soa_project_pocessProvider" portType="client:git_soa_project_pocess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/GIT_SOA_APPLICATION/git_soa_project/git_soa_project_pocess" schemaLocation="XMLSchema_155992767.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="git_soa_project_pocessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="git_soa_project_pocessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="git_soa_project_pocess">
        <wsdl:operation name="process">
            <wsdl:input message="client:git_soa_project_pocessRequestMessage"/>
            <wsdl:output message="client:git_soa_project_pocessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="git_soa_project_pocessBinding" type="client:git_soa_project_pocess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="git_soa_project_pocess_client_ep">
        <wsdl:port name="git_soa_project_pocess_pt" binding="client:git_soa_project_pocessBinding">
            <soap:address location="http://IBASE139.ibaseit.com:12101/soa-infra/services/default/git_soa_project!1.0*soa_27185057-8f63-4c0b-8992-d49660b36418/git_soa_project_pocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>